added MYSQL_LIBRARIES since it defines yaSSL_CTX_free while MYSQL_EMBEDDED_LIBRARIES doesn't (on kubuntu edgy at least), i.e. when mysql is compiled with --with-yassl. This fixes link errors like /usr/lib/mysql/libmysqld.a(client.o): In function `mysql_close_free_options': undefined reference to `yaSSL_CTX_free' It's a workaround imho, but it works.
svn path=/trunk/KDE/kdepim/akonadi/; revision=624122